# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'esc_v1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(400, 300)
        self.MView = QtWidgets.QGraphicsView(Frame)
        self.MView.setGeometry(QtCore.QRect(10, 10, 281, 281))
        self.MView.setObjectName("MView")
        self.SLabel = QtWidgets.QLabel(Frame)
        self.SLabel.setGeometry(QtCore.QRect(310, 170, 59, 16))
        self.SLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SLabel.setObjectName("SLabel")
        self.BButton = QtWidgets.QPushButton(Frame)
        self.BButton.setGeometry(QtCore.QRect(300, 10, 91, 31))
        self.BButton.setObjectName("BButton")
        self.BLabel = QtWidgets.QLabel(Frame)
        self.BLabel.setGeometry(QtCore.QRect(310, 40, 61, 16))
        self.BLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BLabel.setObjectName("BLabel")
        self.formLayoutWidget = QtWidgets.QWidget(Frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(300, 60, 91, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.BLETable = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.BLETable.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.BLETable.setFormAlignment(QtCore.Qt.AlignCenter)
        self.BLETable.setContentsMargins(0, 0, 0, 0)
        self.BLETable.setObjectName("BLETable")
        self.BLE1 = QtWidgets.QLabel(self.formLayoutWidget)
        self.BLE1.setObjectName("BLE1")
        self.BLETable.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.BLE1)
        self.BLE1S = QtWidgets.QLabel(self.formLayoutWidget)
        self.BLE1S.setStyleSheet("background-color: red;")
        self.BLE1S.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BLE1S.setObjectName("BLE1S")
        self.BLETable.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.BLE1S)
        self.BLE2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.BLE2.setObjectName("BLE2")
        self.BLETable.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.BLE2)
        self.BLE2S = QtWidgets.QLabel(self.formLayoutWidget)
        self.BLE2S.setStyleSheet("background-color: red;")
        self.BLE2S.setObjectName("BLE2S")
        self.BLETable.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.BLE2S)
        self.BLE3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.BLE3.setObjectName("BLE3")
        self.BLETable.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.BLE3)
        self.BLE3S = QtWidgets.QLabel(self.formLayoutWidget)
        self.BLE3S.setStyleSheet("background-color: green;")
        self.BLE3S.setObjectName("BLE3S")
        self.BLETable.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.BLE3S)
        self.BLE4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.BLE4.setObjectName("BLE4")
        self.BLETable.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.BLE4)
        self.BLE4S = QtWidgets.QLabel(self.formLayoutWidget)
        self.BLE4S.setStyleSheet("background-color: green;")
        self.BLE4S.setObjectName("BLE4S")
        self.BLETable.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.BLE4S)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Frame)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(300, 190, 91, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Flame = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Flame.setObjectName("Flame")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Flame)
        self.FlameS = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.FlameS.setStyleSheet("background-color: green;")
        self.FlameS.setObjectName("FlameS")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.FlameS)
        self.Gas = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Gas.setObjectName("Gas")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Gas)
        self.GasS = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.GasS.setStyleSheet("background-color: green;")
        self.GasS.setObjectName("GasS")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.GasS)
        self.Vib = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Vib.setObjectName("Vib")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Vib)
        self.VibS = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.VibS.setStyleSheet("background-color: green;")
        self.VibS.setObjectName("VibS")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.VibS)
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(300, 260, 91, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.SLabel.setText(_translate("Frame", "Sensors"))
        self.BButton.setText(_translate("Frame", "Refresh"))
        self.BLabel.setText(_translate("Frame", "Conn Stat"))
        self.BLE1.setText(_translate("Frame", "Patient1"))
        self.BLE1S.setText(_translate("Frame", " "))
        self.BLE2.setText(_translate("Frame", "Patient2"))
        self.BLE2S.setText(_translate("Frame", " "))
        self.BLE3.setText(_translate("Frame", "Patient3"))
        self.BLE3S.setText(_translate("Frame", " "))
        self.BLE4.setText(_translate("Frame", "Patient4"))
        self.BLE4S.setText(_translate("Frame", " "))
        self.Flame.setText(_translate("Frame", "Flame"))
        self.FlameS.setText(_translate("Frame", " "))
        self.Gas.setText(_translate("Frame", "Gas"))
        self.GasS.setText(_translate("Frame", " "))
        self.Vib.setText(_translate("Frame", "Vibration"))
        self.VibS.setText(_translate("Frame", " "))
        self.pushButton.setText(_translate("Frame", "Escape"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

